modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/willkoman/ArcanaTechnica/issues" #optional
[[mods]] #mandatory
modId="arcanatechnica" #mandatory
version="0.2 Indev" #mandatory
displayName="Arcana Technica" #mandatory
updateJSONURL="http://willkostudios.com/api/arcanatechnica/" #optional
displayURL="http://willkostudios.com/mods/arcanatechnica" #optional
logoFile="arcanatechnica.png" #optional
credits="The Mojang and Forge Team" #optional
authors="Willko" #optional
description='''
Magic is here, and it waits to be tamed. Learn about the new mysterious energy in the world.
Learn to channel it's entropy into practical situations like technology, weaponry, and necromancy?!
'''

